### PR TITLE
Migrate away from setup.py

### PR DESCRIPTION
**Pull request by isantop**
Migrates repolib from setup.py to the newer, more standardized pyproject and setup.cfg for the python-build portions. We retain setuptools for now.

### CODE REVIEW

**Comment by isantop** [comment]
As there are no code changes in this repository, testing should center around regression testing and ensuring that all items which should be packaged are correctly included:

- [ ] Ensure that the apt-manage command is present and works
- [ ] Ensure that the python module can be imported from the Python CLI:

```
python3
> import repolib
> repolib.load_all_sources()
> repolib.sources
```
Should show the currently-configured sources

- [ ] Other necessary regression testing.

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
Running `apt-manage` or `sudo apt-manage` outputs:

```
Traceback (most recent call last):
  File "/usr/bin/apt-manage", line 33, in <module>
    sys.exit(load_entry_point('repolib==2.2.1', 'console_scripts', 'apt-manage')())
  File "/usr/bin/apt-manage", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'repolib' has no attribute 'command'
```

Running `python3` outputs:

```
>>> repolib.load_all_sources()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'repolib' has no attribute 'load_all_sources'
>>> repolib.sources
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'repolib' has no attribute 'sources'
```
On install I'm seeing these warnings:

```
dpkg: warning: unable to delete old directory '/usr/lib/python3/dist-packages/repolib/shortcuts': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/python3/dist-packages/repolib/command': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/python3/dist-packages/repolib': Directory not empty
```

**Comment by isantop** [comment]
I was missing a line in the setup file. This should now be fixed

**Comment by n3m0-22** [comment]
I'm still seeing the same issues.

**Comment by isantop** [comment]
> I'm still seeing the same issues.

Yep, I was inadvertently testing on a locally installed copy. Please standby for build system updates

**Comment by isantop** [comment]
@n3m0-22 I believe the issue is now fixed

**Comment by n3m0-22** [comment]
That has resolved the issues. Testing the rest now.

**Comment by n3m0-22** [comment]
When running `apt-manage` to `add` or `remove` without `sudo` there are errors. There is no longer a prompt for the password.  

`apt-manage add` with and without `sudo`:

<details>
<summary>output:</summary>

```
❯ Error: cannot parse D-BUS name from exception: The name is not activatableTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apt-manage", line 33, in <module>
    sys.exit(load_entry_point('repolib==2.2.1', 'console_scripts', 'apt-manage')())
  File "/usr/lib/python3/dist-packages/repolib/command/bin.py", line 91, in apt_manage
    result = command.run()
  File "/usr/lib/python3/dist-packages/repolib/command/add.py", line 266, in run
    util.dbus_quit()
  File "/usr/lib/python3/dist-packages/repolib/util.py", line 262, in dbus_quit
    privileged_object = bus.get_object('org.pop_os.repolib', '/Repo')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```
</details>

`apt-manage remove` without `sudo`:

 <details>
<summary>output:</summary>

```
❯ Error: cannot parse D-BUS name from exception: The name is not activatableTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/repolib/file.py", line 463, in save
    self.path.unlink(missing_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1206, in unlink
    self._accessor.unlink(self)
PermissionError: [Errno 13] Permission denied: '/etc/apt/sources.list.d/popdev-mesa-22-3-5.sources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apt-manage", line 33, in <module>
    sys.exit(load_entry_point('repolib==2.2.1', 'console_scripts', 'apt-manage')())
  File "/usr/lib/python3/dist-packages/repolib/command/bin.py", line 91, in apt_manage
    result = command.run()
  File "/usr/lib/python3/dist-packages/repolib/command/remove.py", line 108, in run
    self.file.remove_source(self.source_name)
  File "/usr/lib/python3/dist-packages/repolib/file.py", line 106, in remove_source
    self.save()
  File "/usr/lib/python3/dist-packages/repolib/file.py", line 468, in save
    privileged_object = bus.get_object('org.pop_os.repolib', '/Repo')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```
</details>

adding and removing a `ppa` without `sudo`:
<details>
<summary>output:</summary>

```
❯ Error: cannot parse D-BUS name from exception: The name is not activatableTraceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apt-manage", line 33, in <module>
    sys.exit(load_entry_point('repolib==2.2.1', 'console_scripts', 'apt-manage')())
  File "/usr/lib/python3/dist-packages/repolib/command/bin.py", line 91, in apt_manage
    result = command.run()
  File "/usr/lib/python3/dist-packages/repolib/command/add.py", line 266, in run
    util.dbus_quit()
  File "/usr/lib/python3/dist-packages/repolib/util.py", line 262, in dbus_quit
    privileged_object = bus.get_object('org.pop_os.repolib', '/Repo')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable

```
</details>

Note:
When adding something like `popdev:mesa-22.3.5` without `sudo` the source is added even with the error, but with `sudo` the error happens as well.

This does not hold true for removal as well as adding and removing a `ppa`. Both always require `sudo`.

**Comment by n3m0-22** [comment]
When I run the ppa tests (e.g., `sudo apt-manage -b add ppa:system76/proposed`) I'm seeing this error.

`apt-manage: ERROR: An error ocurred: PosixPath('/etc/apt/keyrings/ppa-system76-proposed-archive-keyring.gpg')`

**Comment by n3m0-22** [comment]
Using `Tab` to autocomplete for `apt-manage` is no longer working.

**Comment by isantop** [comment]
I believe all of these errors were being caused by missing auxiliary files. I've updated the debian packaging to fix that. 

As a note; it's not possible with the new python packaging to install auxiliary data files to arbitrary system locations (which is by design), so we now catch those errors and inform the user to use sudo instead because of the lack of support. Installations on Pop/from apt should still allow use without sudo as we can install the extra files via the debian package.

> This does not hold true for removal as well as adding and removing a `ppa`. Both always require `sudo`.

This is incorrect; all `apt-manage` commands should work either with or without `sudo` when repolib is installed via apt. This includes installing/removing PPA shortcuts (or any other repository)

**Comment by n3m0-22** [comment]
This does seem to have resolved the issues I was seeing. I will begin further regression testing now.

> > This does not hold true for removal as well as adding and removing a `ppa`. Both always require `sudo`.
> 
> This is incorrect; all `apt-manage` commands should work either with or without `sudo` when repolib is installed via apt. This includes installing/removing PPA shortcuts (or any other repository)

Sorry that I was unclear on this statement. What I meant was that it was not at the time of testing working without `sudo` like it had before. That is also fixed now.

**Review by n3m0-22 — APPROVED** [review]
Everything discussed above is now working correctly. I have gone over the testing checklist as well as any issues that were fixed by previous PRs going back to [Repolib 2 #47](https://github.com/pop-os/repolib/pull/47) and have seen no regressions.

Looks good to me.

Note: There are again a few small changes that need to be made to the `TESTING.md` to account for changes in `repolib`, but nothing that indicates any issues or regressions with `repolib` or `apt-manage` functionality.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
