### PR TITLE
Repolib 2

### PR DESCRIPTION
**Pull request by isantop**
This PR upgrades RepoLib to version 2, which brings support for:

* Multiple DEB822 sources in a single file
* Compliant signing key management (in light of apt-key deprecation)
* A new shortcut for adding Pop_OS staging branches, which adds the correct signing key and pin preferences (Which are removed upon source removal).

This version makes some minor changes to the `apt-manage` command:

* The functionality from the `source` subcommand has been moved to the `modify` subcommand, as there was no reason for this to be handled in its own command
* A new `key` subcommand has been added for adding and removing signing keys

Because this is a breaking change, Repoman will need to be merged first to avoid breakage as the current version does not specify a version requirement for repolib. pop-os/repoman#102 has been created to address this. 

On upgrade to the new version. Repolib will not make any modifications to files on-disk. Corresponding format changes or new keys (where required) will instead be added as sources are modified. New sources will of course be fully-compatible from the get-go.

### CODE REVIEW

**Comment by mmstick** [comment]
> `apt-manage add popdev:master`

Neat. This should make it easy to help people get involved with testing fixes.

**Review by n3m0-22 — COMMENTED** [review]
Testing has mostly passed. The [TESTING.md](https://github.com/pop-os/repolib/blob/master/TESTING.md) file will need to be updated to reflect the changes, but this is working fine with the new commands.

Example:
Old - `sudo apt-manage -b add -d ppa:system76/proposed`
New - `sudo apt-manage -b modify --source-disable ppa-system76-proposed`

There is a potential issue. I need to confirm with @isantop where or not this behavior is expected with the changes.

When adding `sudo apt-manage add deb http://example.com/ubuntu focal main` then name is now `example-com-ubuntu-binary`. Previously it was `deb-example-com-ubuntu`.

**Comment by isantop** [comment]
Yep, looks like the testing proceedure will need to be updated.

**Review by mmstick — APPROVED** [review]

**Review by n3m0-22 — DISMISSED** [review]

**Review by n3m0-22 — APPROVED** [review]
I went through all the testing again this seems to have fixed the issues.

**Comment by isantop** [comment]
I pushed an updated TESTING.md which has been updated for the new version of the commands

**Pull request merged**
