### PR TITLE
Fixes for potential TypeErrors (and related type errors)

### LINKED ISSUE #55: Command crashes when trying to add a malformed source
```
system76@pop-os:~$ apt-manage add pop-dev:isolate-workspaces
Fetching repository information...
Traceback (most recent call last):
  File "/usr/bin/apt-manage", line 82, in <module>
    main()
  File "/usr/bin/apt-manage", line 76, in main
    result = command.run()
  File "/usr/lib/python3/dist-packages/repolib/command/add.py", line 155, in run
    new_source.load_from_data([self.deb_line])
UnboundLocalError: local variable 'new_source' referenced before assignment
```

### PR DESCRIPTION
**Pull request by isantop**
Contains corrections made from static type checking with a type checker. This should eliminate most crashes arising from `TypeError` or `UnboundLocalError` and other related type exceptions.

Fixes #55

### CODE REVIEW

**Review by 13r0ck — APPROVED** [review]

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
I am seeing the new message suggesting a spelling correction when using `pop-dev` instead of `popdev`. I can add a ppa without issue. 

I run into trouble when I try to add any of the github repos. I receive the "Double-check the spelling." message even when it is correct.  

Example:

Input:
`apt-manage add pop-dev:master`
`apt-manage add popdev:master`
`apt-manage add "popdev:master"`

Output for all the above:
```
Fetching repository information...
apt-manage: ERROR: Could not parse line "popdev:popdev-master". Double-check the spelling.
Supported repository shortcuts:
  ppa, popdev
```

Input:
`./pop/scripts/apt add master`

Output:
```
Adding key
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Adding preference for 'master'
Adding repository for 'master'
/usr/bin/apt-manage
Fetching repository information...
apt-manage: ERROR: Could not parse line "deb http://apt.pop-os.org/staging/master jammy main". Double-check the spelling.
Supported repository shortcuts:
  ppa, popdev

```

**Comment by isantop** [comment]
This should now be fixed as of 4bdee37

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
The previous issues have been resolved. I did find a situation where there is not simple error message generated for the user. 

Adding this ppa `apt-manage add ppa:yannick-mauray/quickgui` results in

```
Fetching repository information...
Traceback (most recent call last):
  File "/usr/bin/apt-manage", line 82, in <module>
    main()
  File "/usr/bin/apt-manage", line 76, in main
    result = command.run()
  File "/usr/lib/python3/dist-packages/repolib/command/add.py", line 225, in run
    new_source.get_description(),
  File "/usr/lib/python3/dist-packages/repolib/shortcuts/ppa.py", line 98, in get_description
    output += self.description
TypeError: can only concatenate str (not "NoneType") to str

```

**Comment by isantop** [comment]
> The previous issues have been resolved. I did find a situation where there is not simple error message generated for the user.
> 
> Adding this ppa `apt-manage add ppa:yannick-mauray/quickgui` results in
> 
> ```
> Fetching repository information...
> Traceback (most recent call last):
>   File "/usr/bin/apt-manage", line 82, in <module>
>     main()
>   File "/usr/bin/apt-manage", line 76, in main
>     result = command.run()
>   File "/usr/lib/python3/dist-packages/repolib/command/add.py", line 225, in run
>     new_source.get_description(),
>   File "/usr/lib/python3/dist-packages/repolib/shortcuts/ppa.py", line 98, in get_description
>     output += self.description
> TypeError: can only concatenate str (not "NoneType") to str
> ```

That's technically a type error from Launchpadlib, rather than from Repolib, as in cases where there is no PPA description it returns `None` instead of an empty string. Bad Launchpadlib!

f31c457 provides a workaround for this which should prevent the TypeError by ensuring to only returning a str type.

**Review by n3m0-22 — APPROVED** [review]
Looks good.

**Pull request merged**
