### PR TITLE
Add -y flag to apt-manage add

### PR DESCRIPTION
**Pull request by 13r0ck**
`apt-manage add popdev:branch -y` && `apt-manage add popdev:branch -t` now do the same thing.

### CODE REVIEW

**Review by jacobgkau — COMMENTED** [review]
Should it also be added to the help text on line 40?

**Comment by 13r0ck** [comment]
```
$ apt-manage add --help
usage: apt-manage add [-h] [-d] [-s] [-t] [-n NAME] [-i IDENTIFIER] [-f FORMAT] [-k]
                      [deb_line ...]

positional arguments:
  deb_line              The deb line of the repository to add

options:
  -h, --help            show this help message and exit
  -d, --disable         Add the repository and then set it to disabled.
  -s, --source-code     Also enable source code packages for the repository.
  -t, -y, --terse       Do not display expanded info about a repository before adding it.
  -n NAME, --name NAME  A name to set for the new repo
  -i IDENTIFIER, --identifier IDENTIFIER
                        The filename to use for the new source
  -f FORMAT, --format FORMAT
                        The source format to save as, `sources` or `list`
  -k, --skip-keys       Skip adding signing keys (not recommended!)
```

It doesn't seem to matter, but I added that change anyway

**Review by jacobgkau — APPROVED** [review]
This works for allowing `-y` to bypass the confirmation question when adding a repository. The option being added matches the `apt-manage remove ...` command (that one accepts `-y`, but not `-t`.)

**Comment by jacobgkau** [comment]
> It doesn't seem to matter,

It matters so people can discover the option, that's why the help text exists. It looks good now.

**Comment by 13r0ck** [comment]
Yes that is obvious. You very much misunderstood me.

**Review by isantop — APPROVED** [review]

**Pull request merged**
